version: '3.3'

services:
  frontend:
    build:
      context: .
      args:
        - API_URL=${API_URL:-http://localhost:3000}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - DATABASE_URL=file:/app/data/scanner.db
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    volumes:
      - ${DB_PATH:-./data}:/app/data
    restart: unless-stopped

  prisma-studio:
    build: 
      context: ./server
      dockerfile: Dockerfile.prisma
    ports:
      - "${PRISMA_PORT:-5555}:5555"
    environment:
      - DATABASE_URL=file:/app/data/scanner.db
    volumes:
      - ${DB_PATH:-./data}:/app/data
    depends_on:
      - server
    restart: unless-stopped
