version: '3.8'
services:
  barcode-scanner:
    build:
      context: .
      args:
        - VITE_API_URL=${API_URL}
    container_name: barcode-scanner
    ports:
      - "${PORT_FRONTEND:-4173}:4173"  # Frontend
      - "${PORT_BACKEND:-3002}:3002"   # Backend
    volumes:
      - ./server/data:/app/server/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT_FRONTEND=${PORT_FRONTEND:-4173}
      - PORT_BACKEND=${PORT_BACKEND:-3002}
      - DB_PATH=/app/server/data/scanner.db
      - VITE_API_URL=${API_URL}
    restart: unless-stopped
    user: "node"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
