FROM node:18-slim

WORKDIR /app

# Installation des dépendances système requises pour Prisma
RUN apt-get update && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*

# Installation des dépendances Prisma
COPY package*.json ./
COPY prisma ./prisma/
RUN npm install

# Génération du client Prisma
RUN npx prisma generate

EXPOSE 5555

CMD ["npx", "prisma", "studio", "--port", "5555", "--browser", "none"]
