FROM node:18-slim

WORKDIR /app

# Installation des dépendances système requises pour Prisma
RUN apt-get update && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*

# Installation des dépendances Prisma
COPY package*.json ./
COPY prisma ./prisma/
COPY init-db.js ./
RUN npm install

# Génération du client Prisma
RUN npx prisma generate

EXPOSE 5555

# Script de démarrage pour initialiser la DB si nécessaire
COPY start-prisma.sh ./
RUN chmod +x start-prisma.sh

CMD ["./start-prisma.sh"]
